on:
  workflow_dispatch:
    inputs:
      scope:
        type: choice
        required: false
        description: what to bump (major, minor, patch)
        options:
          - patch
          - minor
          - major
        default: minor

permissions: write-all

jobs:
  bump-manifest:
    name: Bump Manifest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v6

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"

      - name: Bump
        run: |
          npm version ${{ inputs.scope }}
          git push origin main --tags
