on:
  workflow_dispatch:
    inputs:
      scope:
        type: choice
        required: false
        description: what to bump (major, minor, patch)
        options:
          - patch
          - minor
          - major
        default: minor

permissions: write-all

jobs:
  bump-manifest:
    name: Bump Manifest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v6

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"

      - name: Bump
        id: bump
        run: |
          NEW_TAG=$(npm version ${{ inputs.scope }} --tag-version-prefix '')
          git push origin main "${NEW_TAG}"
          echo "tag=${NEW_TAG}" >> "$GITHUB_OUTPUT"

      - name: Create Release
        run: |
          gh release create "${{ steps.bump.outputs.tag }}" --generate-notes --latest
